In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn import svm
import sklearn.tree as tree
from xgboost import XGBClassifier

In [11]:
for y in range(5):
    data = pd.read_csv('WithoutMiss/'+str(y+1)+'year_withoutmiss.csv')
    trainx,testx,trainy,testy = train_test_split(data.iloc[:,0:64], data[u'64'], test_size=0.25, random_state = 0)
    trainy=pd.DataFrame(trainy)
    testy=pd.DataFrame(testy)
    
    model = XGBClassifier(n_estimators=1000).fit(trainx, np.array(trainy).ravel())
    pre=model.predict(testx)
    C = confusion_matrix(testy, pre)
    print(C)
    err = (np.mean((pre != np.array(testy).ravel())))
    print(err)
    
    model = GradientBoostingClassifier(n_estimators=1000).fit(trainx, np.array(trainy).ravel())
    pre=model.predict(testx)
    C = confusion_matrix(testy, pre)
    print(C)
    err = (np.mean((pre != np.array(testy).ravel())))
    print(err)

[[1687    3]
 [  35   32]]
0.0216277746158
[[1685    5]
 [  37   30]]
0.0239043824701
[[2442    4]
 [  62   36]]
0.0259433962264
[[2439    7]
 [  61   37]]
0.0267295597484
[[2503   12]
 [  67   44]]
0.0300837776085
[[2497   18]
 [  69   42]]
0.0331302361005
[[2303   11]
 [  77   57]]
0.0359477124183
[[2291   23]
 [  71   63]]
0.0383986928105
[[1376    8]
 [  37   57]]
0.0304465493911
[[1374   10]
 [  39   55]]
0.0331529093369
